name: Maven Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java environment
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 3: Build with Maven
      - name: Build with Maven
        run: |
          echo "Building with Maven..."
          mvn -f ./pom.xml clean install -Dmaven.wagon.http.timeout=60000

      # Step 4: SSH into Server and Deploy
      - name: SSH into Server and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            echo "Transferring WAR file to server..."
            scp -i ~/.ssh/id_rsa ./target/*.war ubuntu@${{ secrets.HOST }}:/tmp/
            echo "Deploying WAR file to Tomcat..."
            mv /tmp/*.war /opt/tomcat/webapps/
            echo "Restarting Tomcat..."
            sudo systemctl restart tomcat

      # Step 5: Trigger Jenkins Build
      - name: Trigger Jenkins Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.JENKINS_HOST }}
          username: ${{ secrets.JENKINS_USERNAME }}
          key: ${{ secrets.JENKINS_PRIVATE_KEY }}
          port: ${{ secrets.JENKINS_PORT }}
          script: |
            echo "Triggering Jenkins Build..."
            CRUMB=$(curl -u ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }} \
              http://${{ secrets.JENKINS_HOST }}:${{ secrets.JENKINS_PORT }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,":",//crumb))
            curl -X POST http://${{ secrets.JENKINS_HOST }}:${{ secrets.JENKINS_PORT }}/job/${{ secrets.JENKINS_JOB_NAME }}/build \
              --user ${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_API_TOKEN }} \
              -H "$CRUMB"
