name: Java CI/CD with EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-war
          path: target/*.war
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download the WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-war
          path: target/

      - name: Deploy to EC2 using SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            scp target/*.war ubuntu@${{ secrets.HOST }}:/var/lib/tomcat9/webapps/myapp.war
            ssh ubuntu@${{ secrets.HOST }} "sudo systemctl restart tomcat9"

