name: Java CI/CD with EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-war
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download the WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-1.0-SNAPSHOT.war 
          path: target/

      - name: Deploy to EC2
        run: |
          echo "$EC2_KEY" > pro.pem
          chmod 600 pro.pem
          scp -o StrictHostKeyChecking=no -i pro.pem target/myapp-1.0-SNAPSHOT.war ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/var/lib/tomcat9/webapps/myapp.war
          ssh -o StrictHostKeyChecking=no -i pro.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} "sudo systemctl restart tomcat9"


