name: Java CI/CD with EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp-war
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download the WAR artifact
        uses: actions/download-artifact@v3
        with:
          name: myapp-war
          path: target/

      - name: Deploy to EC2
        env:
          EC2_USER: "ec2-user"
          EC2_HOST: "your-ec2-public-ip"
          EC2_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem target/myapp.war $EC2_USER@$EC2_HOST:/home/ec2-user/tomcat/webapps/
          ssh -i private_key.pem $EC2_USER@$EC2_HOST "sudo systemctl restart tomcat"

