name: Java CI/CD with EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-war
          path: target/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download the WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-war
          path: target/

      - name: Create SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Ensure SSH directory exists
        run: mkdir -p ~/.ssh

      - name: Add remote host to known hosts
        run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deploy WAR file to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i ec2-key.pem target/*.war ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/var/lib/tomcat9/webapps/myapp.war

      - name: Restart Tomcat on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} "sudo systemctl restart tomcat9"
