name: Java CI/CD with EC2 Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp-war
          path: target/*.war

  deploy:  # <-- This should be at the same level as 'build'
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download the WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp-war
          path: target/

      - name: Create SSH Key
        run: |
          printf "%s" "${{ secrets.SSH_PRIVATE_KEY }}" > ec2-key.pem
          chmod 600 ec2-key.pem

      - name: Ensure SSH directory exists
        run: mkdir -p ~/.ssh

      - name: Add remote host to known hosts
        run: |
          for i in {1..3}; do
            ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts && break
            sleep 5
          done

      - name: Deploy WAR file to EC2
        run: |
          set -e
          scp -o StrictHostKeyChecking=no -i ec2-key.pem target/*.war ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu/myapp.war
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            sudo mv /home/ubuntu/myapp.war /var/lib/tomcat9/webapps/myapp.war &&
            sudo chown tomcat:tomcat /var/lib/tomcat9/webapps/myapp.war"

      - name: Restart Tomcat on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2-key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} "
            sudo systemctl restart tomcat9 &&
            sudo systemctl status tomcat9 --no-pager"

      - name: Invoke Jenkins Deployment Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://18.209.17.112:8080"
          user: "admin"
          token: ${{ secrets.JENKINS_TOKEN }}
          job: "TomcatDeployment"
